/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("my-plugin")
}

myPlugin {
    check(dependencies.toString() == "extension dependencies") { "dependencies are not extension dependencies, but ${dependencies}" }
}
